services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    networks:
      - fullstack_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5002:5000"
    networks:
      - fullstack_network
    depends_on:
      - selenium
      - selenium-python

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - selenium-python
    networks:
      - fullstack_network

  selenium-python:
    build:
      context: ./scripts
      dockerfile: Dockerfile-python
    container_name: selenium-python
    ports:
      - "5001:5000"
    depends_on:
      - selenium
    networks: fullstack_network

networks:
  fullstack_network:
