services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    networks:
      - fullstack_network

  selenium-python:
    build:
      context: ./scripts # Ruta a la carpeta con tu Dockerfile-python y scripts
      dockerfile: Dockerfile-python
    container_name: selenium-python
    ports:
      - "4445:4444" # Selenium Grid
      - "5001:5000" # Servidor Flask
    shm_size: "2g"
    volumes:
      - ./scripts:/app
    networks:
      - fullstack_network
    depends_on:
      - selenium

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    networks:
      - fullstack_network
    depends_on:
      - selenium
      - selenium-python

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - ../frontend/.env.local:/app/.env.local
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5050
    depends_on:
      - backend
    networks:
      - fullstack_network

  firefox:
    image: jlesage/firefox
    container_name: firefox
    ports:
      - "5800:5800"
    networks:
      - fullstack_network
    volumes:
      - ~/docker/appdata/firefox:/config:rw

networks:
  fullstack_network:
