version: "3"
services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"services:
  backend:
    build: ./backend
    networks:
      - fullstack_network

  frontend:
    build: ./frontend
    networks:
      - fullstack_network

networks:
  fullstack_network:
