# Usa una imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo requirements.txt desde la carpeta actual a /app/scripts en el contenedor
COPY requirements.txt /app/scripts/requirements.txt

# Instala python3-venv para poder crear entornos virtuales
RUN apt-get update && \
    apt-get install -y python3-venv && \
    apt-get clean

# Crea un entorno virtual en /opt/venv
RUN python3 -m venv /opt/venv

# Activa el entorno virtual y actualiza pip
RUN /opt/venv/bin/pip install --no-cache-dir --upgrade pip

# Instala las dependencias dentro del entorno virtual
RUN /opt/venv/bin/pip install --no-cache-dir -r /app/scripts/requirements.txt

# Añade el entorno virtual al PATH
ENV PATH="/opt/venv/bin:$PATH"

ENV FLASK_ENV=development

# Copia todo el código fuente al contenedor
COPY . .

# Expone el puerto donde corre Flask
EXPOSE 5001

# Comando para ejecutar la aplicación
CMD ["python3", "server.py"]