# Usa una imagen ligera de Python
FROM python:3.9-slim

# Instala las dependencias necesarias
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxi6 \
    libxtst6 \
    libxrandr2 \
    libasound2 \
    libpangocairo-1.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libxshmfence1 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

# Instala dependencias de Python
RUN pip install selenium flask

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los scripts desde el directorio backend/scripts
COPY . /app

# Expone el puerto del servidor Flask
EXPOSE 5000

# Comando para iniciar el servidor Flask
CMD ["python", "server.py"]
